### ISSUE TITLE
[combobox] Automatically set default `inputValue` based on `defaultValue`/`value`

### ISSUE THREAD

**Issue by arshad-yaseen** [mui/base-ui#2672]
## Current behavior

I made my combobox controlled using a state, and the state has the default item. When I reload the page, the value/label is not rendered/shown initially in the input, and I want to click on the input and close the popup to show the label in the input.

This is my usage:

```tsx
import { Combobox } from '@/components/combobox';

...

const [value, setValue] = useState({ label: 'Banana', value: 'banana' });

...

<Combobox
     value={value}
     onValueChange={setValue}
     items={[
       { label: 'Apple', value: 'apple' },
       { label: 'Banana', value: 'banana' },
       { label: 'Cherry', value: 'cherry' },
     ]}
/>
```

(Open the reproduction link to see what is inside `@/components/combobox`)

And, This is what is happening:

https://github.com/user-attachments/assets/ad99bbc6-487f-4dd3-9b29-ad3f7e9c1ccb

## Expected behavior

The controlled combobox should show the initial value correctly in the input field on first render.

## Reproducible example

Here is a reproduction: https://stackblitz.com/edit/base-ui-combobox-initial-value-not-working?file=app%2Fpage.tsx

## Base UI version

`^1.0.0-beta.3`

## Which browser are you using?

Chrome

## Which OS are you using?

Mac OS

**Comment by atomiks** [comment]
A couple of things:

1. Make sure that the value referentially matches the one in the items object - so use `items[0]` as the initial state, and define the items object outside the component (or memoize it), which is also better for performance.

```js
const items = [
  { label: 'Apple', value: 'apple' },
  { label: 'Banana', value: 'banana' },
  { label: 'Cherry', value: 'cherry' },
]

export default function Home() {
  const [value, setValue] = useState(items[0]); // referential match

  return (
    <main className="min-h-screen p-8">
      <Combobox
        className="w-fit"
        value={value}
        onValueChange={setValue}
        items={items}
      />
    </main>
  );
}
```

2. The default `inputValue` currently needs to be manually aligned with the default `value` (whether controlled or uncontrolled):

```js
<Combobox
  className="w-fit"
  value={value}
  onValueChange={setValue}
  items={items}
  // Align the input value to the initial value's label
  defaultInputValue={items[0].label}
/>
```

I was aware of needing to manually align the input value (since comboboxes maintain two independent values - one for the selected value, and one for the input), but if it's confusing, we can try to change it so it gets auto-derived from the value initially instead.

**Comment by arshad-yaseen** [comment]
> Make sure that the value referentially matches the one in the items object - so use items[0] as the initial state, and define the items object outside the component (or memoize it), which is also better for performance.

We are already memoizing and matching referentially in our original codebase. The code in the reproduction link was just for reproduction. By the way, thanks for the information!!

> Align the input value to the initial value's label

It's good and okay, but one doubt: What if `multiple` is enabled, then what should be the value of `defaultInputValue`, array of labels? Because in the `multiple` case, we will not show label(s) in input. Just to confirm xD

> we can try to change it so it gets auto-derived from the value initially instead.

Would be very nice, much better DX!

**Comment by atomiks** [comment]
Oh, alright 👍 there were some bugs in the demo caused by that, so just making sure that reference issues are fixed as well 

`multiple` uses chips instead, while the input value is empty. For single-selection mode, the input is filled with the current value's label.

> Would be very nice, much better DX!

I think it makes sense to auto-derive when both `defaultInputValue` and `inputValue` are `undefined` specifically, but otherwise respect them

**Comment by arshad-yaseen** [comment]
> `multiple` uses chips instead, while the input value is empty. For single-selection mode, the input is filled with the current value's label.

Perfect! Got it!

**Comment by arshad-yaseen** [comment]
Working as expected when using `defaultInputValue`. So closing the issue.

**Comment by atomiks** [comment]
We should keep it open specifically for this change

> I think it makes sense to auto-derive when both defaultInputValue and inputValue are undefined specifically, but otherwise respect them



I'll make a PR next week to address this and close it with the PR

**Comment by mgray88** [comment]
<strike>The merged PR indicates a fix for this was part of the v1.0.0-beta.4 release? I'm still experiencing this issue with that release</strike>

Apologies, I think I forgot to restart Storybook after updating 🫠

**Comment by atomiks** [comment]
@mgray88 to be fair, you made me realize the solution fails to handle an edge case: it doesn't work if you change the `value` after first mount. For example with Fast Refresh, the change is not properly reflected when editing `value` (or programmatically updating it at some time). Though setting `key` on the root does force it to reflect the new input value as a workaround.

**Comment by shiqocred** [comment]
Changes do not take effect in the multiple combobox for now in version 1.1.0. Each combobox is rendered without triggering `onValueChange`, which automatically results in the log showing an empty array `[]` at the end every time, and this also causes the value to become an empty array `[]`. The `defaultInputValue` solution does not work either.

```tsx
<Combobox
  multiple
  autoHighlight
  items={categories}
  value={fields.map((f) => f.data)}
  onValueChange={(e) => {
    replace(e.map((i) => ({ data: i })));
  }}
  defaultInputValue={fields.map((f) => f.data)}
>
  <ComboboxChips ref={anchor} className="w-full col-span-full">
    <ComboboxValue>
      {(values) => {
        console.log(values);
        return (
          <React.Fragment>
            {values.map((value: any) => (
              <ComboboxChip key={value}>
                {
                  categories.find((i) => i.id === value)?.nama
                    .id
                }
              </ComboboxChip>
            ))}
            <ComboboxChipsInput />
          </React.Fragment>
        );
      }}
    </ComboboxValue>
  </ComboboxChips>
  <ComboboxContent anchor={anchor}>
    <ComboboxEmpty>No items found.</ComboboxEmpty>
    <ComboboxList>
      {(item: CategorySelectType) => (
        <ComboboxItem key={item.id} value={item.id}>
          {item.nama.id}
        </ComboboxItem>
      )}
    </ComboboxList>
  </ComboboxContent>
</Combobox>
```

*I’m using it that way because react-hook-form adds a unique ID when the data is an array, and that really interferes with the selected indicator.

Here’s the translation:

 I can work around it with:

 ```tsx
 onValueChange={(e) => {
   if (!e || e.length === 0) return;

   replace(e.map((i) => ({ data: i })));
 }}
```

But this is very bad because multiple data cannot be removed completely down to an empty array `[]`.

**Comment by atomiks** [comment]
@shiqocred you might be facing a different issue: https://github.com/mui/base-ui/issues/3865

In 1.1.0:

1. If the selected item isn't in the `items` array, it automatically gets cleared. It also has to match referentially (`===`/`Object.is`). If the object isn't the same, it will get cleared unless using `isItemEqualToValue`. This has changed in the next version so "orphan" selected values don't need to be in the `items` array
2. Several internal operations assume the shape of `items` matches what's passed to `<Combobox.Item value={...}>`. Proper support for primitive keys with object items is being added in #3954 

If you try that version, which contains both fixes, your setup may "just work"

```
npm i https://pkg.pr.new/mui/base-ui/@base-ui/react@3954
```
