### ISSUE TITLE
[popover] Maximum update depth exceeded when assigning ref

### ISSUE THREAD

**Issue by KingSora** [mui/base-ui#3275]
# Bug report

I'm using the popover trigger component like this:

```js
<Popover.Trigger
	render={(triggerProps) => {
	  return (
		<button
		  {...triggerProps}
		  ref={(value) => {
			assignRef(triggerProps.ref, value);
		  }}
		/>
	  );
	}}
>
   <BellIcon aria-label="Notifications" className={styles.Icon} />
</Popover.Trigger>
```

Where the `assignRef` function is a simple function to assign refs (in case I want the ref value to be assigned to multiple refs for example):

```ts
import type { Ref, ForwardedRef, MutableRefObject, RefCallback } from 'react';

export const assignRef = <T>(
  ref: ForwardedRef<T> | Ref<T> | MutableRefObject<T> | RefCallback<T> | undefined,
  value: T | null,
) => {
  if (ref) {
    if (typeof ref === 'function') {
      ref(value);
    } else if (typeof ref === 'object') {
      ref.current = value;
    }
  }
};
```

## Current behavior

Using the `assignRef` function in the `ref` function like shown above will throw an `Maximum update depth exceeded` error.

## Expected behavior

No `Maximum update depth exceeded` error when using the `assignRef` function.

## Reproducible example

https://stackblitz.com/edit/fccxhcji?file=src%2FApp.tsx,src%2FassignRef.ts

## Base UI version

1.0.0-beta.6

## Which browser are you using?

Doesnt matter

## Which OS are you using?

Doesnt matter

## Which assistive tech are you using (if applicable)?

Doesnt matter

## Additional context

This was working back in version 1.0.0-beta.3 and was probably introduced in the "detached triggers" effort.

**Comment by atomiks** [comment]
Yes it's almost certainly related to #3245 which was already fixed. 

The latest preview release can be used in the meantime / to confirm the fix:

```shell
pnpm i https://pkg.pr.new/@base-ui-components/react@d78ce4c
```

Also fwiw, you should probably always memoize `ref` callback functions. This isn't possible if you don't control the code (like `react-router`/TanStack router, which have the issue), but still. In that case, the `ref` needs to be placed on the component rather than inside the render function

**Comment by KingSora** [comment]
@atomiks thanks for the quick reply! Will the fix also be released as a "hotfix" (like beta.6) in the near future or will it be included in a regular release which will take a bit longer?

**Comment by atomiks** [comment]
@KingSora the plan for the next releases was more frequent already since we're preparing v1. The detached triggers feature was the last major change to the component internals that created breaking changes

- `rc.0` on November 26 (next Wednesday)
- `1.0.0` on December 10, if nothing comes up

In the meantime, you can use that preview release (which addresses several of the known regressions) until the RC version next week, or otherwise temporarily stay on beta.4

**Comment by michaldudak** [comment]
@KingSora, can you confirm https://pkg.pr.new/@base-ui-components/react@d78ce4c fixes your issue?

**Comment by KingSora** [comment]
@atomiks @michaldudak I've tested the linked version and can confirm that it fixes the issue. 

I've found one more interesting thing in that version, although it only happens with older browser where `Object.hasOwn` is not supported. In those browsers I'm still getting the same error but worse, because the whole tab freezes like with a `while(true) {}` loop. The cause is that any function with `Object.hasOwn` throws (because its not supported by the browser) and this seems to still cause the issue / infinity loop.

**Comment by atomiks** [comment]
`Object.hasOwn(...)` is ["Baseline Widely Available"](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwn) which is the supported versions of browsers we'll be using going forward

If you need to support older than "Baseline Widely Available" polyfilling `Object.hasOwn` seems necessary

**Comment by KingSora** [comment]
@atomiks I know, just wanted to mention it, since it doesnt just throw an error but freezes the whole tab / browser.
